### ISSUE TITLE
Toggling reinforcement

### ISSUE THREAD

**Issue by thesnaake** [Exultant/Citadel#104]
Looking for on/off toggle for reinforcement groups. Reinforcement for crops is great, however this prohibits clearing crops with water. The ability to temporarily disable reinforcement on a given group would be extremely helpful, and I am sure others would feel the same.

**Comment by ttk2** [comment]
Its an intentional tradeoff. Protected crops or ease of harvesting. Not
both.

**Comment by thesnaake** [comment]
Works for me. Thanks!
