### ISSUE TITLE
CTB no longer saves it's state across sessions

### ISSUE THREAD

**Issue by Sanwi** [Exultant/Citadel#107]
It's so annoying to have to check whether or not /ctb is on every time I relog. I used to have a macro that just typed it when I logged in, but sometimes it's saved across sessions now. It's annoying as fuck; I had to make a macro that types /ctb, reads chat to see if it turned on or off, then does it again if it needs to.

**Comment by ttk2** [comment]
so the error name should be it now somtimes saves across sessions?

**Comment by Sanwi** [comment]
Actually, yeah. I would _like_ a command for it. Either way, just being predictable would be nice.
