### ISSUE TITLE
Piston bug 1:

### ISSUE THREAD

**Issue by ttk2** [Exultant/Citadel#2]
Piston bug 1: When one moves a reinforced bock with a piston, then the block will be moved, but the reinforcement will not change locations.  Thus, the moved block will lose its reinforcement, unless, of course, it is moved back to its previous location, in which case it will re-gain its reinforcement.  Bugs 1 and 2 are relate:reinforcement is based on location, and not the block itself.

**Comment by Freenor** [comment]
I suggest shelving this issue for now and simply making fortified blocks non-pistonable.  This will speed up release, and allow us to gradually port the code over from <x,y,z,world> identification over to "block" identification (do individual blocks have individual ID's? I'm new to this modding thing ... if so, it may make sense to simply make the change NOW).

**Comment by ttk2** [comment]
That was the proposed solution. If anyone can implement it it would close this bug.

**Comment by Freenor** [comment]
I don't know anything about Minecraft's Item or System level ID's.  But if someone does, these should be used as keys instead of location coordinates.  Otherwise, we'll have to come up with an ad-hoc fix for every single situation (doors, pistons, etc.).

**Comment by ttk2** [comment]
Since minecraft is closed sourced from what i understand we are in the dark as to its internal memory structure and no matter how appealing it may be to try and add values to the blocks themselves instead of doing it via external databases it may not be possible.
