### ISSUE TITLE
Assigning programmers to Isses?

### ISSUE THREAD

**Issue by ttk2** [Exultant/Citadel#21]
To prevent cross coding i would encourage contributors to assign themselves to a particular Issue so that everyone knows who is doing what.

**Comment by Exultant** [comment]
Issues may or may not be discrete.

**Comment by ttk2** [comment]
I am aware of that, the problem is that Gu3rilla, Chrisrico and Chx all started working on different solutions to the same problem. Gu3rilla's solution is done and in the comments for the TNT bugs, i have not seen the other two yet. And i guess it will not be too much of a problem to simply try them all and see which one does the job the best. But i cant help but think it would be better if we could code one solution to each problem in the future. Although considering that the nature the TNT bug requires more changes to program structure than the others it may be a one time thing anyways.
