### ISSUE TITLE
Tell user object is protected

### ISSUE THREAD

**Issue by ttk2** [Exultant/Citadel#23]
Report to the user the [user information](https://github.com/Exultant/Citadel/wiki/Plugin-Goals) message described on the goals page when they attempt to destroy a protected block. Otherwise it feels too much like lag and players may become confused.

**Comment by egokick** [comment]
There is the hidden benefit that griefers joining the server that are not familiar with it will assume everything is protected and give up, but it would be nice to be able to see which blocks are reinforced.  What do you think about a toggleable command such as "/ctcount on" when typed you left click once on a block and it will tell you how many reinforcements it has left. Ideally it would be typed once and then work for every block that you click until you log out, saying nothing when a block does not have any reinforcements to prevent spam to the user and typing "ctcount off" removes it. 

Does citadel store info about who put the reinforcement upon a block? What do you think about also letting people see who put the reinforcement upon it? I think that may go some way to discourage griefing by placing reinforced blocks around peoples chests/doors, but it could also take away from the realism if someone wants to build a secret hideout somewhere and doesn't want to be known.

**Comment by ttk2** [comment]
No username, just information about the block, maybe /ctexamine as a toggle command? I am not sure if the database currently stores the max value of the reinforcement, so the message may require that to be stored as well to calculate a percent.

**Comment by ghost** [comment]
added in d5f93dff, see /ctinfo
