### ISSUE TITLE
Piston bug 2: 

### ISSUE THREAD

**Issue by ttk2** [Exultant/Citadel#3]
Piston bug 2: When a piston is reinforced, then extended, the piston head can be destroyed, which causes the piston base to be destroyed.  The piston head is not reinforced.

**Comment by ttk2** [comment]
Low priority. But should be rather similar to the code used to allow the protection of doors and chests as single blocks when they occupy two block spaces.

**Comment by Freenor** [comment]
A simple fix for this would be to reinforce the location "one ahead" of the business end of a piston.  The only problem is that pistons themselves are pushable, so if someone builds extremely complicated machinery it could generate a lot of database lag.

One way to get around such lag in general is to build a "buffer" for the reinforcement system.  This buffer would build up requests, or whatever, and then "flush" each tick by concatenating together into a single UPDATE call to pass through the DAO.  This would allow for pistons to move around and move their protections around based on the existing <x,y,z,world> block ID system that we use now.

**Comment by ttk2** [comment]
If its a significant amount of work abandon it and simply make pistons unprotected.

**Comment by Freenor** [comment]
In my opinion that should be the policy _for now_. We can eventually change that through the test server, but there's no reason to demand this work for launch.
