### ISSUE TITLE
multiple groups?

### ISSUE THREAD

**Issue by Rudd-O** [Exultant/Citadel#30]
unfortunately pbgroup is not enough because you might want to have different groups for different teams that you associate with, so you can secure things in a different way.

can you give a feature where we can create more than one group?  that way everyone can secure outer perimeters on behalf of citadel without having to add everyone in our city to their group.

**Comment by ghost** [comment]
This is a planned feature.

**Comment by JonnyD** [comment]
I'm currently working on it.

**Comment by JonnyD** [comment]
Groups have been implemented in latest commit.
