### ISSUE TITLE
Mob Spawner protection does not work properly 

### ISSUE THREAD

**Issue by ttk2** [Exultant/Citadel#31]
As reported by Straight Foolish

"To make a long story short, I had a spawner which was only iron-enforced at first (due to lack of a diamond on hand). The plan was to come back later and reinforce it better (using /ctbypass).
I used /cti first to make sure the spawner was reinforced. It was, so I typed /ctbypass and broke the block. Normally this returns the iron used and the block remains (so that I could reinforce it with diamond instead). Instead, the spawner broke and the iron was not even returned. Ouch. Lots of hours sunk into building the device around the grinder, and the supporting infrastructure."

**Comment by ttk2** [comment]
This is a result of the disabled ctupgrade functionality, this was possible before.
To clarify for the OP, only some blocks work the way you were expecting. Chests and dispensers will pop the protection resource on the first break with /ctbypass but will not pop the block itself.
Most all other blocks will.
It seems like unretrievable blocks need to be changed to work like chests with regards to cbypass.
That would be spawners, bookshelves, glowstone, and ore blocks (if they can be protected at all)
This would solve the issues created by the disabling of ctr upgrades.

Credit Go1dfish

**Comment by funknut** [comment]
Any chance this might be added as a feature in a newer release?  Nice work on Citadel.  Great plugin.  Release this on bukkit.org and watch its popularity soar.
