### ISSUE TITLE
Fortified stone bricks with stone burns up extra stone brick

### ISSUE THREAD

**Issue by cwillu** [Exultant/Citadel#33]
On the civcraft server:

I've set my quick-bar up with 4 stacks of stone brick, and 4 stacks of stone, and set /ctf to use the stone to fortify.  

For every fortified stone brick I place, the quick bar shows 2 stone bricks and 1 stone being used: the stack I'm placing from decrements for a moment, then increments; at the same time, a stone and a stone-brick from a different stack decrement.  A moment later, the count from the stack I'm placing decrements as well.  

This makes fortification much more expensive than it should be.

**Comment by intangir** [comment]
still exists.. pretty major

**Comment by intangir** [comment]
i think this was fixed
