### ISSUE TITLE
Usage of Linux filesystem permissions for protected blocks

### ISSUE THREAD

**Issue by orthzar** [Exultant/Citadel#36]
Currently, Citadel has very simple and very limited permissions and group capabilities.  Linux, on the other hand, allows very sophisticated groups and permissions.  I propose implementing a Linux file system permissions scheme inside of Citadel.  Each block would be treated as a file.
- Protected blocks are owned by a player and only associated with a group if the player declares it so (/cgroup make <group>).
- An owner of a block can change the group that a block is associated with at any time(/cgroup add_block <group>).
- A block has three categories of permission: owner permissions, group permission (/cgroup add_player <group> <###>), and everyone else's permissions (/cother <###>)
- Players can own groups, in addition to blocks.
- The owner always has read-write-execute permissions, and can only change that if he sells the block/group.
- Ownership of a block/group can be transferred only by the owner to anyone else (/ctransfer <group_name>/block <player>).  Each block that you touch after passing the "/ctransfer block ttk2", transfers the ownership of those blocks to ttk2.
- Every group can have blocks associated with it and each group can have groups nested inside of them.
- The owner of a group can change in what group it is nested, but only if that group-owner has permissions to place his group in the other group.

My command suggestions, in parentheses, are a bit convuluted, though it might be appropriate to simply adapt the Linux chmod, chgrp, and chown.

Very important: There must be no admin capacities, so that ttk2 and Hexapus remain in the same situation regarding Citadel: they can't do anything that other players can't do.

**Comment by JonnyD** [comment]
I'm currently working on a solution to groups that allows for an owner and moderators. Would that do? Unfortunately, I don't think it's possible to do anything more complicated until a map reset when the design of the database can be improved without affecting existing records. The problem is some database tables are too tightly coupled and there are nearly 2 million reinforced blocks, it would be too risky to move database entries around.
