### ISSUE TITLE
Impenetrable-chest bug:

### ISSUE THREAD

**Issue by ttk2** [Exultant/Citadel#4]
Impenetrable-chest bug: When a player places a chest having never run any Citadel command, then that chest will be indestructible to all other players.  When that player breaks the chest, it will be broken as though it were never protected.  Further, a very strange message is sent to any player that so much as left-clicks on such an impenetrable chest.

**Comment by ttk2** [comment]
When a player types /ctpublic and places a chest, other players cannot access that chest. Basically, a player in public mode nevertheless places chests that are affected by Impenetrable-chest bug.

**Comment by Freenor** [comment]
I can't find any place in the code where "public", "private", or "group" status of the placer plays any role in reinforcement. I think this is a section of code that chx intended to extend upon, but did not.

**Comment by ttk2** [comment]
For chests it should, judging from the original state of citadel chest protection is not very fleshed out.

**Comment by ghost** [comment]
Fixed in d5f93dff. The default for fortification and reinforcement modes is now Private.
