### ISSUE TITLE
Is there a jenkins? Where do I find the jar I cant find the bukkitdev page.

### ISSUE THREAD

**Issue by LordZeroHour** [Exultant/Citadel#41]
Just trying to find the plugin or plugin wiki.

Thanks,
LZH

**Comment by ttk2** [comment]
There is no bukkitdev page and there is no compiled jar sitting around as part of the project. This plugin exists solely for this server, if you wish to take upon yourself publishing it and maintaining builds feel free but the only existing jars are on the Civcraft server and the Civcraft test server.

**Comment by Rudd-O** [comment]
## We do not push any jars on the internet. Just compile it locally using eclipse. 

Sent from my Android phone with K-9 Mail. Please excuse my brevity.

LordZeroHour reply@reply.github.com wrote:

Just trying to find the plugin or plugin wiki.

Thanks,
LZH

---

Reply to this email directly or view it on GitHub:
https://github.com/Exultant/Citadel/issues/41
