### ISSUE TITLE
ctremovereinforcements command doesn't work

### ISSUE THREAD

**Issue by FreyaFrei** [Exultant/Citadel#46]
I haven't tried this myself. But I asked someone who was quitting if he could remove all of his reinforcements. He typed the command, but nothing happened.

**Comment by ttk2** [comment]
That code is not in the citadel version running on the production server.

**Comment by JonnyD** [comment]
Yeah that was only there to give developers a quick and easy access to deleting ALL the reinforcements.

**Comment by FreyaFrei** [comment]
It's still listed in the help on page 2. I'm not sure if there is any way to remove it though. Can't wait for the new citadel when we can transfer ownership and we won't have this problem with people leaving the game anymore.
