### ISSUE TITLE
/cti fails to show reinforcement information for iron and wooden doors 

### ISSUE THREAD

**Issue by ttk2** [Exultant/Citadel#54]
/cti fails to show reinforcement information for iron and wooden doors when they are secured such that you are unable to open them (ie, someone else has private-reinforced them or they are group-reinforced for a group you are not a member of)

This bug has been around for some months and is still reproducible by using /cti and clicking on a door you are unable to open

Issue filed on behalf of Alex9002

**Comment by remyroy** [comment]
I'll have a look at this one.

**Comment by remyroy** [comment]
This is fixed in change 6b07316 part of pull request 55.
