### ISSUE TITLE
Naturally reinforced blocks 

### ISSUE THREAD

**Issue by ttk2** [Exultant/Citadel#71]
To better simulate the real would some block should be naturally reinforced. For example Iron may take 15 breaks before you are done mining it. 

This feature has ram caching as a prerequisite as otherwise resource consumption during regular play would be far to high for a server implementation to function well. Fortunately the current repository already has this feature included if not well tested. 

As for how this feature should function, on start up Citadel should load a set of block id's and durability values from the config file that are supposed to be naturally reinforced. To allow natural blocks to be reinforced always without overloading the database Citadel will not search for lets say all the Iron blocks in the map and add them to the database on its first run, this is far too resource intensive, instead it is simpler to add a IF statement to where Citadel already catches all block break events to check if the block is reinforced. If someone breaks an iron ore block and citadel finds no entry in the database for it it should proceed to create a reinforcement entry with the configured durability value minus one. 

In this way natural blocks are added to the database only as needed and there is no costly search for the blocks locations up front.

**Comment by intangir** [comment]
Eww, sounds like a bad idea, and a bad implimentation plan

**Comment by ttk2** [comment]
If we could just change the block break times in Minecraft that would be great, but we can't so this is the best alternative. 

Whats wrong with the implementation? If its missing details or needs to be put somewhere else feel free to comment on that, but when it comes to adding natural blocks to the database it almost has to be done lazily as the block are interacted with by players as opposed to trying to find every block up font, the resource consumption from that strategy is just massive.

**Comment by intangir** [comment]
Why are the block break times even being increased?

**Comment by ttk2** [comment]
Balance changes, one of the biggest issues with veins is how fast they can be mined out, this helps resolve that issue.

**Comment by intangir** [comment]
why not remove veins? Or make them smaller and/or fewer

**Comment by ttk2** [comment]
That would defeat their other purposes to provide a point of congregation and conflict over resources. Its like asking why Citadel does not just do area of affect protection despite it being much less database intense. If we coded games to be efficient with no regard for game-play or mechanics we would still be playing pong.

**Comment by intangir** [comment]
Is this a plan for the next iteration of the world or for the current world?

**Comment by ttk2** [comment]
Next iteration, it will be immediately implemented in the next round of Civtest. This has been discussed a good bit both on the subreddit and in our email mailing list.

**Comment by intangir** [comment]
I don't understand the reasons for the veins or making it more tedious to
mine.

But I would not use the db to handle these blocks at all

Could have it init an array for break counts on included ores within a
chunk the first time a block is broken within the chunk and remember it
until the chunk is unloaded. Never save it to db, if it is unloaded before
breaking completely it just starts over

This doesn't even need to be included as part of citadel. It doesn't need
db support or user level permissions
I think it should be standalone

**Comment by ttk2** [comment]
If the counts are not persistent it could have interesting affects on the
way people mine and prevent them from let's say trading shifts mining
because there is no way to organize a proper transition.

**Comment by intangir** [comment]
How many breaks are you planning to require?

**Comment by ttk2** [comment]
Its unknown at this point. The right values are going to take some
tinkering to find. But for high value things like diamond it may be
impractical if you have to ensure that you are not going to be bothered for
the next 10 minutes just to mine one block. Persistence lets people tag
team the blocks in shifts without having to make sure the chunk does not
get unloaded.

**Comment by intangir** [comment]
I really really don't like the sound of these changes. People have certain
expectations in the game and this is a drastic change from those
expectations, for the worse imo (the tedium level is going to outweigh
"fun") also how much crafting can you do if you take forever to mine useful
blocks

I don't know how this change could do anything other than contribute to the
decline of civcraft.. I am concienciously objecting and withdrawling my
expertise from this particular new feature ;)

**Comment by ttk2** [comment]
Its important to take features in context. You are looming at it lime
single player instead of the multiplayer situation we have where working
together the whole tech tree is a piece of cake that requires serious
changes.

People have given expectations of Minecraft like griefing being bannable
and admins resolving disputes. I don't really bother with keeping to
expectations.

**Comment by intangir** [comment]
There are limits to what can accomplish on this game engine.

There are also limits to what game play elements people will tolerate.

**Comment by ttk2** [comment]
We have been looking into Game engines to get to work on soon. 

As for game play elements its all about how its balanced and implemented, that's what Civtest is for. 

Have you seen my post on Civtest round 2? Its going to be a gold rush style map just to test this feature.

**Comment by intangir** [comment]
Haven't seen it. I am interested in the new engine project. I hope it is
cross platform and has features to support massive multiplayer

**Comment by nickelpro** [comment]
Do you want the reinforcement to be randomly applied, applied to all ores of that type or...?

I'll look at it when I get back from work, though I haven't actually spent much time digging through the citadel source before now

**Comment by ttk2** [comment]
I want it applied in a configurable amount to configured ores.
