### ISSUE TITLE
Double chest protection glitch

### ISSUE THREAD

**Issue by ttk2** [Exultant/Citadel#8]
If you have a protected chest and you place another chest next to it the resulting double chest can be opened by any player by right clicking on the newly placed block. 

This brings up an interesting question, should double chests require two of what ever resource to lock? Or do they get to piggyback onto the protection of the first part of the chest.

**Comment by Azlinea** [comment]
Is there a way to make it piggyback on the first chest but still send a break event towards the first chest's durability?

Ex. 2 people go at two different sides of a chest that has 10 durability left. When person A breaks the original side it decrements the durability 1 to 9 total and when person B breaks the add on side it decrements the durability 1 to 8 total.

**Comment by Freenor** [comment]
Should require double-resources to lock, of course.  Each block should be separately registrable.  This is the easiest fix possible; requires no change of the code base, and adds the intuitive constraint that double-protection = double-cost.

Azlinea points out an interesting route, however, worth investigating more carefully.  We could break the current Reinforcement system into 2 parts: 1 part storing reinforcement entries themselves (their durability level), and 1 storing mappings from (x,y,z,world) locations back to ID's in the first table.  This would mean that one "reinforcement" could extend to the two blocks of a chest, and the calculations done to decrement durability would be done against the Reinforcement table directly.  This could propagate deductively to all blocks tied to that Reinforcement entry by their own entries in the 2nd table (individual block reinforcements). 

This solution would mean complicating some matters though, such as the fix I proposed for the TNT bug.  All that'd have to change is that a lookup for Reinforced blocks in an area would have to perform a simple JOIN between the two tables I described above.

In such a scenario, whenever a block is damaged, you check to see if it's reinforced.  If so, then you update the reinforcement.  I may not be very clever about this, but it looks like 2 queries to me where we could do it with 1.  It would be a pain when people forget to reinforce both parts of the block, but we could solve something like this with a simpler solution like POSTING A HUGE WARNING COMMENT IN THE TERMINAL WHENEVER SOMEONE REINFORCES OR EXTENDS A CHEST TO MAKE SURE THEY DON'T FORGET.

**Comment by ttk2** [comment]
Lets take the double cost route, otherwise single chests will have no purpose at all, everyone will create double chests for the 'free' protection on the extra room.

**Comment by Freenor** [comment]
I concur with ttk2.

**Comment by ghost** [comment]
I think that introduces more difficulties than it's worth. For instance, say you have a reinforced single chest and you place another chest next to it. Does that require reinforcement material to do so? In d5f93dff I both clone the reinforcement if a second chest is placed and check for a neighboring chest reinforcement on interaction. In my next commit I will remove the first part and leave only the neighbor check.

**Comment by ttk2** [comment]
that's the idea.

**Comment by ghost** [comment]
That seems like a poor user experience that they are not able to place a chest (while not explicitly in reinforcement or fortification mode) unless they have the correct material in their inventory. I really don't think the relatively small increase in cost is worth the increased complexity.

**Comment by ttk2** [comment]
The idea was that the chest would simply not merge (but instead remain two separate directly adjacent chests) and then they would become a double chest when the other one is reinforced with the same material. But i do agree it does create difficulties. So its far from essential.

**Comment by ghost** [comment]
Hmm... if they were seperately reinforced, what happens when one of the reinforcements is broken? Then they can open the whole chest from one side?

Anyway, close this if you feel like, or leave it open if you still want to change how chests are handled.

**Comment by ttk2** [comment]
They break exactly like vanilla chests do, when a vanilla chest breaks it drops the half of the items in that chest and leaves the other half of the items in the side that was not broken.

**Comment by ghost** [comment]
Hmm, ok. Currently I have securable things (doors, containers and anything set in the config) becoming merely unlocked when the reinforcement is broken. If you want to break it, you then have to break it an additional time. Such chests could just break immediately.
