### ISSUE TITLE
Locked doors still able to be opened

### ISSUE THREAD

**Issue by Azlinea** [Exultant/Citadel#9]
Caveat: What part of the door is protected and what part is unprotected might be reversed.

When you protect a door currently only the bottom of the door is protected meaning that if you right click the top half or set a redstone torch next to the top half then the door will open. I vaguely remember Chx mentioning that instead of locking/protecting at the block level that he should change it to the...Item level or system level? Whatever encapsulates all of the blocks in an item if its size is more than 1 block.

**Comment by Freenor** [comment]
There's a solution to this within the system Chx handed us (using coordinates instead of item/system level IDs).  Whenever a door is placed, reinforce the block directly above it as well.  

In other words, if you reinforce (x,y,z,w) and it's also a door, then reinforce (x,y+1,z,w) by default.

**Comment by ghost** [comment]
Fixed in d5f93dff. For doors, beds, and double chests, the reinforcement is stored on only one of the two blocks. This is because you're always interacting with the whole and not the part, so it makes no sense to have two separate reinforcements.
