### ISSUE TITLE
Make item frames reinforcable 

### ISSUE THREAD

**Issue by remyroy** [Exultant/Citadel#91]
[Item frame](http://www.minecraftwiki.net/wiki/Item_frame) is a new item that was introduced in 1.4.2. It enables someone to display any item in a frame and change the frame direction. Currently, they cannot be reinforced.

Reinforced item frame should:
- Make them take more hits before they can be broken based on the material used for the reinforcement.
- Make it impossible for those who do not have access to put, remove or change the item in the item frame.
- Make it impossible for those who do not have access to change the direction of the item frame.
- Increase its break damage. With vanilla, they have the same break damage as a torch which even if it is reinforced with diamond can be broken quite fast.

**Comment by ttk2** [comment]
probably somewhat significant. Lets get this done and baked into the build for the bukkit beta R03 api break.

**Comment by erocs** [comment]
These will need looking at. I'm sure there will be others as entities don't act like blocks. As for breaking them slower, we can't adjust break times, only add break counts.

PlayerInteractEntityEvent, HangingBreakEvent, HangingBreakByEntityEvent, HangingPlaceEvent, BlockPistonExtendEvent, BlockPistonRetractEvent, BlockPlaceEvent, BlockPhysicsEvent, CreatureSpawnEvent, PlayerBucketEmptyEvent

**Comment by intangir** [comment]
why is creaturespawnevent in the list?

also if this is going to be added we should also make it apply to storage minecarts

**Comment by erocs** [comment]
creaturespawnevent == creation of golems and the wither

**Comment by erocs** [comment]
https://mojang.atlassian.net/browse/MC-712

This is an interesting bug to take into consideration. Fences cause item frames to pop off the wall.
