### ISSUE TITLE
placing stone fortified with stone only costs 1 stone on 1.4.6

### ISSUE THREAD

**Issue by intangir** [Exultant/Citadel#96]
not sure why 1.4.6 somehow breaks it.
it works in 1.4.5 but in 1.4.6 it suddenly doesn't work the same

my guess is it tries to delete the same piece that was already removed.. so i think for the special case of fortifying stone, with stone, we will have to delete 2 stones.. im gonna try it.. very odd

**Comment by erocs** [comment]
Were you in creative mode?

**Comment by intangir** [comment]
no
try it out
i tried it on civtest even

**Comment by intangir** [comment]
i made a fix but for the life of me i cant figure out how to use god damn github/git

**Comment by intangir** [comment]
i made a seperate thread with the pull request
